const Series = {
  AlkaliMetals: "Alkali Metals",
  AlkalineEarthMetals: "Alkaline Earth Metals",
  Lanthanoids: "Lanthanoids",
  Actinoids: "Actinoids",
  TransitionMetals: "Transition Metals",
  PostTransitionMetals: "Post-transition Metals",
  Metalloids: "Metalloids",
  ReactiveNonmetals: "Reactive Nonmetals",
  NobleGases: "Noble Gases",
  Unknown: "Unknown"
};

const Groups = {
  Metals: [ Series.AlkaliMetals, Series.AlkalineEarthMetals, 
            Series.Lanthanoids, Series.Actinoids,
            Series.TransitionMetals, Series.PostTransitionMetals ],
  Metalloids: [ Series.Metalloids ],
  Nonmetals: [ Series.ReactiveNonmetals, Series.NobleGases ]
}

const element = (number, symbol, name, series) => {
  return {
    Number: number,
    Symbol: symbol,
    Name: name,
    Series: series,
  };
}

const Elements = [
  element(1, "H", "Hydrogen", Series.ReactiveNonmetals),
  element(2, "He", "Helium", Series.NobleGases),
  element(3, "Li", "Lithium", Series.AlkaliMetals),
  element(4, "Be", "Beryllium", Series.AlkalineEarthMetals),
  element(5, "B", "Boron", Series.Metalloids),
  element(6, "C", "Carbon", Series.ReactiveNonmetals),
  element(7, "N", "Nitrogen", Series.ReactiveNonmetals),
  element(8, "O", "Oxygen", Series.ReactiveNonmetals),
  element(9, "F", "Flourine", Series.ReactiveNonmetals),
  element(10, "Ne", "Neon", Series.NobleGases),
  element(11, "Na", "Sodium", Series.AlkaliMetals),
  element(12, "Mg", "Magnesium", Series.AlkalineEarthMetals),
  element(13, "Al", "Aluminum", Series.PostTransitionMetals),
  element(14, "Si", "Silicon", Series.Metalloids),
  element(15, "P", "Phosphorus", Series.ReactiveNonmetals),
  element(16, "S", "Sulfur", Series.ReactiveNonmetals),
  element(17, "Cl", "Chlorine", Series.ReactiveNonmetals),
  element(18, "Ar", "Argon", Series.NobleGases),
  element(19, "K", "Potassium", Series.AlkaliMetals),
  element(20, "Ca", "Calcium", Series.AlkalineEarthMetals),
  element(21, "Sc", "Scandium", Series.TransitionMetals),
  element(22, "Ti", "Titanium", Series.TransitionMetals),
  element(23, "V", "Vanadium", Series.TransitionMetals),
  element(24, "Cr", "Chromium", Series.TransitionMetals),
  element(25, "Mn", "Manganese", Series.TransitionMetals),
  element(26, "Fe", "Iron", Series.TransitionMetals),
  element(27, "Co", "Cobalt", Series.TransitionMetals),
  element(28, "Ni", "Nickel", Series.TransitionMetals),
  element(29, "Cu", "Copper", Series.TransitionMetals),
  element(30, "Zn", "Zinc", Series.TransitionMetals),
  element(31, "Ga", "Gallium", Series.PostTransitionMetals),
  element(32, "Ge", "Germanium", Series.Metalloids),
  element(33, "As", "Arsenic", Series.Metalloids),
  element(34, "Se", "Selenium", Series.ReactiveNonmetals),
  element(35, "Br", "Bromine", Series.ReactiveNonmetals),
  element(36, "Kr", "Krypton", Series.NobleGases),
  element(37, "Rb", "Rubidium", Series.AlkaliMetals),
  element(38, "Sr", "Strontium", Series.AlkalineEarthMetals),
  element(39, "Y", "Yttrium", Series.TransitionMetals),
  element(40, "Zr", "Zirconium", Series.TransitionMetals),
  element(41, "Nb", "Niobium", Series.TransitionMetals),
  element(42, "Mo", "Molybdenum", Series.TransitionMetals),
  element(43, "Tc", "Technetium", Series.TransitionMetals),
  element(44, "Ru", "Ruthenium", Series.TransitionMetals),
  element(45, "Rh", "Rhodium", Series.TransitionMetals),
  element(46, "Pd", "Palladium", Series.TransitionMetals),
  element(47, "Ag", "Silver", Series.TransitionMetals),
  element(48, "Cd", "Cadmium", Series.TransitionMetals),
  element(49, "In", "Indium", Series.PostTransitionMetals),
  element(50, "Sn", "Tin", Series.PostTransitionMetals),
  element(51, "Sb", "Antimony", Series.Metalloids),
  element(52, "Te", "Tellurium", Series.Metalloids),
  element(53, "I", "Iodine", Series.ReactiveNonmetals),
  element(54, "Xe", "Xenon", Series.NobleGases),
  element(55, "Cs", "Caesium", Series.AlkaliMetals),
  element(56, "Ba", "Barium", Series.AlkalineEarthMetals),
  element(57, "La", "Lanthanum", Series.Lanthanoids),
  element(58, "Ce", "Cerium", Series.Lanthanoids),
  element(59, "Pr", "Praseodymium", Series.Lanthanoids),
  element(60, "Nd", "Neodymium", Series.Lanthanoids),
  element(61, "Pm", "Promethium", Series.Lanthanoids),
  element(62, "Sm", "Samarium", Series.Lanthanoids),
  element(63, "Eu", "Europium", Series.Lanthanoids),
  element(64, "Gd", "Gadolinium", Series.Lanthanoids),
  element(65, "Tb", "Terbium", Series.Lanthanoids),
  element(66, "Dy", "Dysprosium", Series.Lanthanoids),
  element(67, "Ho", "Holmium", Series.Lanthanoids),
  element(68, "Er", "Erbium", Series.Lanthanoids),
  element(69, "Tm", "Thulium", Series.Lanthanoids),
  element(70, "Yb", "Ytterbium", Series.Lanthanoids),
  element(71, "Lu", "Lutetium", Series.Lanthanoids),
  element(72, "Hf", "Hafnium", Series.TransitionMetals),
  element(73, "Ta", "Tantalum", Series.TransitionMetals),
  element(74, "W", "Tungsten", Series.TransitionMetals),
  element(75, "Re", "Rhenium", Series.TransitionMetals),
  element(76, "Os", "Osmium", Series.TransitionMetals),
  element(77, "Ir", "Iridium", Series.TransitionMetals),
  element(78, "Pt", "Platinum", Series.TransitionMetals),
  element(79, "Au", "Gold", Series.TransitionMetals),
  element(80, "Hg", "Mercury", Series.TransitionMetals),
  element(81, "Tl", "Thallium", Series.PostTransitionMetals),
  element(82, "Pb", "Lead", Series.PostTransitionMetals),
  element(83, "Bi", "Bismuth", Series.PostTransitionMetals),
  element(84, "Po", "Polonium", Series.PostTransitionMetals),
  element(85, "At", "Astatine", Series.Metalloids),
  element(86, "Rn", "Radon", Series.NobleGases),
  element(87, "Fr", "Francium", Series.AlkaliMetals),
  element(88, "Ra", "Radium", Series.AlkalineEarthMetals),
  element(89, "Ac", "Actinium", Series.Actinoids),
  element(90, "Th", "Thorium", Series.Actinoids),
  element(91, "Pa", "Protactinium", Series.Actinoids),
  element(92, "U", "Uranium", Series.Actinoids),
  element(93, "Np", "Neptunium", Series.Actinoids),
  element(94, "Pu", "Plutonium", Series.Actinoids),
  element(95, "Am", "Americium", Series.Actinoids),
  element(96, "Cm", "Curium", Series.Actinoids),
  element(97, "Bk", "Berkelium", Series.Actinoids),
  element(98, "Cf", "Californium", Series.Actinoids),
  element(99, "Es", "Einsteinium", Series.Actinoids),
  element(100, "Fm", "Fermium", Series.Actinoids),
  element(101, "Md", "Mendelevium", Series.Actinoids),
  element(102, "No", "Nobelium", Series.Actinoids),
  element(103, "Lr", "Lawrencium", Series.Actinoids),
  element(104, "Rf", "Rutherfordium", Series.TransitionMetals),
  element(105, "Db", "Dubnium", Series.TransitionMetals),
  element(106, "Sg", "Seaborgium", Series.TransitionMetals),
  element(107, "Bh", "Bohrium", Series.TransitionMetals),
  element(108, "Hs", "Hassium", Series.TransitionMetals),
  element(109, "Mt", "Meitnerium", Series.Unknown),
  element(110, "Ds", "Damstadium", Series.Unknown),
  element(111, "Rg", "Roentgenium", Series.Unknown),
  element(112, "Cn", "Copernicium", Series.Unknown),
  element(113, "Nh", "Nihonium", Series.Unknown),
  element(114, "Fl", "Flerovium", Series.Unknown),
  element(115, "Mc", "Moscovium", Series.Unknown),
  element(116, "Lv", "Livermorium", Series.Unknown),
  element(117, "Ts", "Tennessine", Series.Unknown),
  element(118, "Og", "Oganesson", Series.Unknown),
];

export { Elements, Series, Groups };